# Generated by Django 3.1.3 on 2020-11-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('strength', models.CharField(max_length=5)),
                ('image_url', models.URLField(blank=True, max_length=1024)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
