# Generated by Django 3.1.3 on 2020-11-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
