# Generated by Django 3.1.3 on 2020-11-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='image_url',
        ),
    ]
