# Generated by Django 3.1.3 on 2020-11-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_coffee_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coffee',
            new_name='Beans',
        ),
    ]
