# Generated by Django 3.1.3 on 2020-11-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201104_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beans',
            new_name='Bean',
        ),
    ]
