# Generated by Django 3.1.3 on 2020-11-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201104_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bean',
            new_name='Beans',
        ),
    ]
