# Generated by Django 3.1.3 on 2020-11-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201104_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beans',
            options={'verbose_name_plural': 'Beans'},
        ),
    ]
