# Generated by Django 3.1.3 on 2020-11-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201104_1616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beans',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
