# Generated by Django 3.1.3 on 2020-11-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201104_2124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Bean',
        ),
    ]
