# Generated by Django 3.1.3 on 2020-11-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201105_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
