# Generated by Django 3.1.3 on 2020-11-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_bean_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='size',
            field=models.CharField(choices=[('small', 'SMALL'), ('large', 'LARGE')], default='small', max_length=6),
        ),
    ]
