# Generated by Django 3.1.3 on 2020-11-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_bean_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bean',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bean',
            name='size',
        ),
        migrations.AddField(
            model_name='bean',
            name='large_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bean',
            name='small_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
