# Generated by Django 3.1.3 on 2020-11-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201110_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
