# Generated by Django 3.1.3 on 2020-11-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_bean_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bean',
            old_name='large_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='bean',
            name='small_price',
        ),
    ]
