# Generated by Django 3.1.3 on 2020-11-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20201111_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='bean',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
