# Generated by Django 3.1.3 on 2020-11-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_bean_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bean',
            old_name='country',
            new_name='bag_size',
        ),
        migrations.RemoveField(
            model_name='bean',
            name='large_price',
        ),
        migrations.RemoveField(
            model_name='bean',
            name='small_price',
        ),
        migrations.AddField(
            model_name='bean',
            name='country_name',
            field=models.CharField(default=False, max_length=254),
        ),
    ]
