# Generated by Django 3.1.3 on 2020-11-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20201118_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='name',
        ),
    ]
