# Generated by Django 3.1.3 on 2020-11-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20201118_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bean',
            name='description',
        ),
        migrations.AddField(
            model_name='bean',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(default=False),
        ),
    ]
