# Generated by Django 3.1.3 on 2020-11-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
