# Generated by Django 3.1.3 on 2020-11-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_country_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bean',
            name='strength',
        ),
        migrations.AddField(
            model_name='country',
            name='strength',
            field=models.CharField(default=3, max_length=5),
        ),
    ]
